name: twilio
description: A Package that helps with twilio API. Supports to send twilio programmable SMS and retrive all messages data from twilio.
version: 0.0.2
repository: https://github.com/denishnavadiya123/Twilio.git
homepage: https://github.com/denishnavadiya123/Twilio.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.4
  intl: ^0.17.0

